kind: Service
apiVersion: v1
metadata:
  name: web-port
  namespace: kubeleans
spec:
  type: NodePort
  selector:
    app: kubeleans-webapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30000 # This is required by Kubernetes to be in the range 30000-32767